import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { FormProvider } from "@/components/FormContext";
import { Kanit } from 'next/font/google';

const kanitFont = Kanit({
  subsets: ['latin'], // Specify subsets
  weight: ['400'], // Specify weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${kanitFont.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <FormProvider>
          <Header />
          {children}
        </FormProvider>
      </body>
    </html>
  );
}
